export const toDoActions = {
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
    FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE'
};

export const filterActions = {
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
};
